DELETE FROM FACT_DetalleVenta
GO
DBCC CHECKIDENT ('[FACT_DetalleVenta]', RESEED, 0)
GO

DELETE FROM DIM_Articulo
GO
DBCC CHECKIDENT ('[DIM_Articulo]', RESEED, 0)
GO

DELETE FROM DIM_Fecha
GO
DBCC CHECKIDENT ('[DIM_Fecha]', RESEED, 0)
GO