INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Tarapacá');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Antofagasta');    
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Atacama');        
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Coquimbo');       
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Valparaíso');     
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de O`Higgins');   
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región del Maule');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región del Biobío');        
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de la Araucanía');   
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de los Lagos');      
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Aysén');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Magallanes');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región Metropolitana');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de los Ríos');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Arica');
INSERT INTO core_region VALUES (seq_id_region.nextval, 'Región de Ñuble');

INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Iquique', 1);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Alto Hospicio', 1);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pozo Almonte', 1);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Antofagasta', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Mejillones', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Taltal', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Calama', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Pedro de Atacama', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Tocopilla', 2);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Copiapó', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Caldera', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Tierra Amarilla', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chañaral', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Salvador', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Diego de Almagro', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Vallenar', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Huasco', 3);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Serena', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Tongoy', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coquimbo', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Andacollo', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Vicuña', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Illapel', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Vilos', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Salamanca', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Ovalle', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Combarbalá', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Monte Patria', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Palqui', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Punitaqui', 4);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Valparaíso', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Placilla de Peñuelas', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Casablanca', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Concón', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puchuncaví', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Las Ventanas', 5);        
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quintero', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Viña del Mar', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hanga Roa', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Andes', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Calle Larga', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Rinconada', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Esteban', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Ligua', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cabildo', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quillota', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Calera', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hijuelas', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Cruz', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Melón', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Nogales', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Antonio', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Mirasol - El Yeco', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Algarrobo', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cartagena', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Quisco', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Las Cruces', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Tabo', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santo Domingo', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Felipe', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Catemu', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Llaillay', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Putaendo', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santa María', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Villa los Almendros', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quilpué', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Limache', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Olmué', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Villa Alemana', 5);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Rancagua', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Codegua', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Doñihue', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coltauco', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lo Miranda', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Doñihue', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Graneros', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Las Cabras', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Machalí', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Francisco de Mostazal', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Punta', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Gultro', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Punta de Diamante', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Peumo', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pichidegua', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quinta de Tilcoco', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Rengo', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Lirios', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Requínoa', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Vicente de Tagua Tagua', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pichilemu', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Fernando', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chépica', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chimbarongo', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Nancagua', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Peralillo', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santa Cruz', 6);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Talca', 7);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Constitución', 7);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Maule', 7);       
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Culenar', 7);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Clemente', 7);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cauquenes', 7);   
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Curicó', 7);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hualañé', 7);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Molina', 7);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Rauco', 7);       
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Romeral', 7);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Teno', 7);        
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Linares', 7);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Colbún', 7);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Longaví', 7);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Parral', 7);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Retiro', 7);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Javier', 7);  
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Villa Alegre', 7);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Concepción', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coronel', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chiguayante', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hualqui', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lota', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Penco', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Pedro de la Paz', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santa Juana', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Talcahuano', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Tomé', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hualpén', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lebu', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Laraquete', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Arauco', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cañete', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Curanilahue', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Álamos', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Ángeles', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cabrero', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Monte águila', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Laja', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Mulchén', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Nacimiento', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Rosendo', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santa Bárbara', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Huépil', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Yumbel', 8);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Labranza', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Temuco', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Carahue', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cunco', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Freire', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Gorbea', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lautaro', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Loncoche', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Nueva Imperial', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Padre las Casas', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pitrufquén', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pucón', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Vilcún', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cajón', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Villarrica', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Angol', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Collipulli', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Curacautín', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Purén', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Renaico', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Traiguén', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Victoria', 9);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Alerce', 10);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puerto Montt', 10);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Calbuco', 10);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Fresia', 10);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Frutillar', 10);   
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Muermos', 10); 
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Llanquihue', 10);  
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puerto Varas', 10);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Castro', 10);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Ancud', 10);       
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chonchi', 10);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Dalcahue', 10);    
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quellón', 10);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Osorno', 10);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Purranque', 10);   
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Río Negro', 10);   
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chaitén', 10); 
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coyhaique', 11);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puerto Aysén', 11);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cochrane', 11);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chile Chico', 11);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Punta Arenas', 12);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puerto Williams', 12);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Porvenir', 12);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puerto Natales', 12);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Santiago', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cerrillos', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Cerro Navia', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Conchalí', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Bosque', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Estación Ccentral', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Huechuraba', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Independencia', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Cisterna', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Florida', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Granja', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Pintana', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Reina', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Las Condes', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lo Barnechea', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lo Espejo', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lo Prado', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Macul', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Maipú', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Ñuñoa', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pedro Aguirre Cerda', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Peñalolén', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Providencia', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pudahuel', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Ciudad del Valle', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Qulicura', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quinta Normal', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Recoleta', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Renca', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Joaquín', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Miguel', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Ramón', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Vitacura', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Puente Alto', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Pirque', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Principal', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San José de Maipo', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La obra - Las Vertientes', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Colina', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chicureo', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chamisero', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Batuco', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lampa', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Valle grande', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chicauma', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Tiltil', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Bernardo', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Alto Jahuel', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Buin', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Bajos de San Agustín', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Paine', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Hospital', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Bollenar', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Melipilla', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Curacaví', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Talagante', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'El Monte', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Isla de Maipo', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Islita', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Padre Hurtado', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Peñaflor', 13);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Valdivia', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Lanco', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Los Lagos', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San José de la Mariquina', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Paillaco', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Panguipulli', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'La Unión', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Futrono', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Río Bueno', 14);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Arica', 15);
INSERT INTO core_ciudad VALUES (270, 'Parinacota', 15);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Putre', 15);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chillán', 16);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Bulnes', 16);       
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Chillán Viejo', 16);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quillón', 16);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Yungay', 16);       
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Quirihue', 16);     
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coelemu', 16);      
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'San Carlos', 16);
INSERT INTO core_ciudad VALUES (seq_id_ciudad.nextval, 'Coihueco', 16);

commit;